apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: us-east1
    failure-domain.beta.kubernetes.io/zone: us-east1-b
  name: pvc-3a202db9-ea40-11e8-8766-42010a8e00c7
  selfLink: /api/v1/persistentvolumes/pvc-3a202db9-ea40-11e8-8766-42010a8e00c7
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: uw-mongo-mongodb
    namespace: default
    resourceVersion: "182817"
    uid: 3a202db9-ea40-11e8-8766-42010a8e00c7
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-uw-cluster-f283d3f-pvc-3a202db9-ea40-11e8-8766-42010a8e00c7
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
status: {}
