language: node_js
branches:
  only:
  - master
  - "/^PR-.+$/"
git:
  quiet: true
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- "./.version.sh"
- "./compose.sh"
- yarn add global -W lerna
install:
- yarn install --ignore-scripts
- yarn prepare
before_script:
- yarn seed
