language: node_js
node_js:
- 9
sudo: true
branches:
  only:
  - master
  - "/^PR-.+$/"
cache:
  name: shared
  directories:
  - $HOME/google-cloud-sdk
  - ~/_uw_data
  - ~/_uw_esdata
  - node_modules
  yarn: true
services:
- docker
git:
  quiet: true
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_COMPUTE_ZONE=$GCLOUD_ZONE
  - CLOUDSDK_CORE_PROJECT=$GCLOUD_PROJECT
  - secure: hkh92DkZ1zko11+fPcRNPvjq62FtkehQmYfN9O80RjvYUd6oDYKoE2lwdAYpEeM7FqXOQB5ShJrCDxLWyp/7RXbx5UlImYxWYhQgJAjL6zkJ11WmZTnX3kwdTpfn3eABkqLpoMVH9v0dvpjMqTYGXPuzR6K7u9kfiufPSezU2obeh8yKPjV3wxTRth6Tky9abhyFUjTcwzbIWXLiRNrhV9YhZCFu3RdfMcNfW9AXkHMhxaPGUKKjTFJD60rVlwb17of4S7SrjCWPO0KCxP7ERTWosD/LXToE7k7PbIOK821+O3Ze1nEdPDmuK6mkCnsIthnMOSP/4hpje31sz/0pXdktytkFbh4EDl+2nCKYMHLzqIfpbgAwr8wEyToY+G3MkFS/CdlnbhBCIRD3USng47wvFzrka39f7KZ2ycB0IKVbb0GDsfvrsXWBvzMdt/2ZTIwMSB7igzuu5YD7plqgniyB/ffE/L8+J1/X4m0Zjb/KiFeOa0eDDaFx4oOjg8NIJ8FE7tw3kGnxKK9deHbuvLze7Khfz7MFnBc3fB5fNjQKzXwCG9vs7/5/gTzRQw+oxVy2T5+qg+5ECtXj1cGCDz1hGStaMuBmQ9GANW9Zx6QF+RCOVcFiYxJCwee/UbqQ78puRJEjSPWL9Vedj2NC4AcusvivlptgGnskD1tLjhM=
before_install:
- |
  if [[ $TRAVIS_PULL_REQUEST == “false” ]] && [[ $TRAVIS_BRANCH == “master” ]]; then
    . ./auth-gcloud.sh
    . ./version.sh
    travis_terminate 0
  else
    yarn global add lerna
    go get github.com/josephburnett/jd
    mkdir -p ~/_uw_data
    mkdir -p ~/_uw_esdata
    sudo chown -R 999:999 ~/_uw_data
    sudo chown -R 1000:1000 ~/_uw_esdata
    . ./compose.sh
    yarn
    yarn seed
    yarn test
  fi
intall: true

# Optimise cache
# https://www.randomerrata.com/articles/2013/travis-s3/
