language: node_js
node_js:
- 9
sudo: true
branches:
  only:
  - master
  - "/^PR-.+$/"
cache:
  if: branch != master
  name: shared
  directories:
  - $HOME/google-cloud-sdk
  - ~/_uw_data
  - ~/_uw_esdata
  - node_modules
  yarn: true
services:
- docker
git:
  quiet: true
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_COMPUTE_ZONE=$GCLOUD_ZONE
  - CLOUDSDK_CORE_PROJECT=$GCLOUD_PROJECT
  - secure: Ho5L+pft+69TcWarsWIgj5tx6i/yyb1l7JQrLD0zZQSwEP4dFyCABbTIAUkXwnc03IWghpvR9taLLX9K/pW/Jkx5cWd1H8Dh9uhb2TDdeJWaa9h4D5rxwWuwOOUJaRA7U0VUYYk1zede6Fjv5D6UHH8lgwx9bEmSobMJ5CbnXSNFhejWU/Dvj9BfS2v5TPCA1wEa8OlX8DybFQB0uvn9dJ+FpVy9fTMTg/qHnTBMpb3cmZ53G2Vqbdu3jvq4yahSULA+V1n4ZWrxahMw9g9cbKBvLXU8ItXMxvDWi0gPJCE3kT1suBS8PfDYcajPBrfA3Mi7tcwHzJeMuEua1CI9fwOY0cpSBNUVfh+VayJgRJ3Tg1NAHtthByAXT9/yvuL+axwz0So6xST1jy4wdLpkamZ/mNqngJB+SwNbudn+J3LVOwFlzDWOg2+VSzEY4cO0oT37kO0p2B74E8nR6ECmdq1q4v8E/qYifL/h9CQD2IPI3yAnVP2/YOBgnSVfxtaAJK2htAwNx9czrTef+EPhsVwYsLFcq0quzjnuhd9cqFxcie77mbYcxzFmlnXRBYZJUKZuHSdYFVgdLjsGVPvWzeS0rq3a9AM62/2Ea+9cirwPU4MAML2kmoB1hmJdZcLkkLA+heYT5wXLxGNq3nXZ/kfI6w4di9L5A+PzhElZMZU=
before_install:
- |
  echo TRAVIS_PULL_REQUEST $TRAVIS_PULL_REQUEST
  echo TRAVIS_BRANCH $TRAVIS_BRANCH
  yarn global add lerna
  go get github.com/josephburnett/jd
  if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == master ]]; then
    . ./.auth-gcloud.sh
    . ./.version.sh
  else
    mkdir -p ~/_uw_data
    mkdir -p ~/_uw_esdata
    sudo chown -R 999:999 ~/_uw_data
    sudo chown -R 1000:1000 ~/_uw_esdata
    . ./compose.sh
    yarn
    yarn seed
    yarn test
  fi
install: true

# Optimise cache
# https://www.randomerrata.com/articles/2013/travis-s3/
