language: node_js
branches:
  only:
  - master
  - "/^PR-.+$/"
git:
  quiet: true
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- "./.version.sh"
- "./compose.sh"
- yarn add global -W lerna
install:
- yarn install --ignore-scripts
- yarn prepare
before_script:
- yarn seed
env:
  global:
    secure: KfZwzHCzzQX4YSFk94h+Tpv3jQiU/R6gDSGHug+07YQxb7jVHtuz9GNrgOWZtGSGsz0Klpb0uVm8GPPCg0FysxY32V3m+nCDnpawE8Jk8XhlQXeF6ISVsSF4TydCQ92m76hZdoTiOoI7rivKTtGpRrBinmjr6/ad0u3ZtCgasPzhrCC0wxf56H3wHdy7qe6kjOixm71VXDCEMqrf/HiimMlaTdVqje5oHXNEeRXJ9epIkl56/UMe7Znuml2qQ84Z4IuE+IISOPh3ajQYTfnKzc4UHUvSLX+vf0ifThl2uftVqwN6EeTZGtc8bwXFN6Q6WZXNZLRC3OLiMEQC6cGlAwHGbJolez+sus2IkkKoJwEzMNxupgv3mFe8GOeLuJmBM1csIDje67haU2fFEW7a9wiFsd57hjUO1k+GCXndIg2P/jMgihkIWve122N+j2ycq8GZHX+Q+D0hyQ85/ydolj12eh667McyWNs9aViwlB2aT27ARBkse0M/kAaKXzKEStflQ6bLrpSi2p1XbIhiv/8vlVXH9dLoqrdw27cAemHuMzZF97p6WTcdESk2k7BuqiByBbcHFfMnd0OacIEYkdOXdZZr5FFcteYLMXKGrmdRA0CxUWTCHWqZTrvcjF4CgqmZX5KTQbjAIFlaiJzY3jPuwmdhW8MvdnbDqtwJf1U=
