language: node_js
branches:
  only:
  - master
  - "/^PR-.+$/"
git:
  quiet: true
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- "./.version.sh"
- "./compose.sh"
- yarn add global -W lerna
install:
- yarn install --ignore-scripts
- yarn prepare
before_script:
- yarn seed
env:
  global:
  - secure: FArgJZkomzM+Y1f0Y2qp69xqqJIxnRe99S/sHyLD3VjziGDrPtzLAH1HWpMXL1iesaAL0FeFi5N0/m34F9hFA4QUrjGOcK2kUXUqBADrOH+pzyawSZvEl0ZGeJis7KXf3Hq16YkkUzvbIjfKeNhJqU6tZBwdRcoaxxRmZROVBp7tAhnm5JnV0Lm4DJaVkQ2DWA4A7iHQtMaoMG81T5LHDXSCHg34A7lITXDuLgt558y06DoMTzNTD7Kz4lEzWq6MwpjyuWOGhhUtWAFp4csjbJO4U+KAXCRIfzen5JZmZVKOpCkEze4gijJTwnhExB2/bWi/E4lWl7gzPiZlXy6R7BXyQ1Ku/x+aDWDu94RaYbfxAC8B7qDV/gL5i6AwB4yw0ao4KjzQAbI0XVIhtlXuwtzy4CxP95+3/ycPGtGusLS0CVLSxSGix4RGjn02Va6SRJCPx6I3MDIiwkK4oDHtuHJS2tspC131wcBcFHSzyXTEtDKGnPNYUAfV1WNXxFa8sAMW+LqqCeBvSuHhQ7n5l3hJq8zEfIrFRoa94/usumvdRJQkp/Z3zhCLQR0le8fMb79C8JhyWPvbgS9ovJaAtb8aNfpqw58d18/23C7bgthujrGwmP0K6f/e+3bbvj3gGv6K6mT82Hv/GNx9uZXaAYxJMhK9LC6PlmpIv3D6rJw=
