language: node_js
before_install:
  - sudo killall mongod
  - sudo killall elastcsearch
  - ./compose.sh
  - yarn add global -W lerna
install:
  - yarn install --ignore-scripts
  - yarn prepare
  - yarn seed
