language: node_js
node_js:
- 9
branches:
  only:
  - master
  - "/^PR-.+$/"
cache:
  directories:
  - "$HOME/google-cloud-sdk"
  - "$HOME/docker"
  - /var/lib/docker
  - node_modules
  yarn: true
services:
- docker
git:
  quiet: true
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_COMPUTE_ZONE=us-east1-b
  - CLOUDSDK_CORE_PROJECT=unicode-wiki
  - secure: hkh92DkZ1zko11+fPcRNPvjq62FtkehQmYfN9O80RjvYUd6oDYKoE2lwdAYpEeM7FqXOQB5ShJrCDxLWyp/7RXbx5UlImYxWYhQgJAjL6zkJ11WmZTnX3kwdTpfn3eABkqLpoMVH9v0dvpjMqTYGXPuzR6K7u9kfiufPSezU2obeh8yKPjV3wxTRth6Tky9abhyFUjTcwzbIWXLiRNrhV9YhZCFu3RdfMcNfW9AXkHMhxaPGUKKjTFJD60rVlwb17of4S7SrjCWPO0KCxP7ERTWosD/LXToE7k7PbIOK821+O3Ze1nEdPDmuK6mkCnsIthnMOSP/4hpje31sz/0pXdktytkFbh4EDl+2nCKYMHLzqIfpbgAwr8wEyToY+G3MkFS/CdlnbhBCIRD3USng47wvFzrka39f7KZ2ycB0IKVbb0GDsfvrsXWBvzMdt/2ZTIwMSB7igzuu5YD7plqgniyB/ffE/L8+J1/X4m0Zjb/KiFeOa0eDDaFx4oOjg8NIJ8FE7tw3kGnxKK9deHbuvLze7Khfz7MFnBc3fB5fNjQKzXwCG9vs7/5/gTzRQw+oxVy2T5+qg+5ECtXj1cGCDz1hGStaMuBmQ9GANW9Zx6QF+RCOVcFiYxJCwee/UbqQ78puRJEjSPWL9Vedj2NC4AcusvivlptgGnskD1tLjhM=
before_install:
- sudo apt-get update
- sudo apt-get json_diff
- "./.version.sh"
- "./.deploy.sh"
- "./compose.sh"
- yarn add global -W lerna
install:
- yarn install --ignore-scripts
- yarn prepare
before_script:
- yarn seed
# after_success:
# - "./.version.sh"
# - "./.deploy.sh"
