export const NOTIFICATION = "@@Notification"
export const SET_NOTIFICATION = "SET_NOTIFICATION"
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION"
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS"
