version: "3"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.1
    volumes:
      - ./config/kibana:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    # command: ["curl", ""]

networks:
  elk:
