apiVersion: v1
kind: Service
metadata:
  labels:
    run: uw-app-web
  name: uw-app-web
spec:
  clusterIP: 10.35.250.227
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30644
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: uw-app-web
  sessionAffinity: None
  type: LoadBalancer
