apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: uw-api-web
  name: uw-api-web
spec:
  replicas: 1
  selector:
    matchLabels:
      run: uw-api-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: uw-api-web
    spec:
      containers:
      - image: gcr.io/unicode-wiki/uw-api:0.0.1
        imagePullPolicy: IfNotPresent
        name: uw-api-web
        ports:
        - containerPort: 3001
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30


      # apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   labels:
#     run: uw-api-web
#   name: uw-api-web
# spec:
#   revisionHistoryLimit: 3
#   replicas: 1
#   selector:
#     matchLabels:
#       run: uw-api-web
#   strategy:
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 1
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         run: uw-api-web
#     spec:
#       containers:
#       - image: gcr.io/unicode-wiki/uw-api:0.0.11
#         imagePullPolicy: IfNotPresent
#         name: uw-api-web
#         ports:
#         - containerPort: 3001
#           protocol: TCP
#         resources: {}
#         terminationMessagePath: /dev/termination-log
#         terminationMessagePolicy: File
#       dnsPolicy: ClusterFirst
#       restartPolicy: Always
#       schedulerName: default-scheduler
#       securityContext: {}
#       terminationGracePeriodSeconds: 30
