apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: uw-app
  annotations:
    kubernetes.io/ingress.global-static-ip-name: uw-app-ip
  labels:
    app: uw-app
spec:
  backend:
    serviceName: uw-app-backend
    servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: uw-app-api
  labels:
    app: uw-app
spec:
  type: NodePort
  selector:
    app: hello
    tier: web
  ports:
  - port: 8080
    targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: unicode-wiki
  labels:
    app: uw-app
spec:
  selector:
    app: uw-app
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "35.231.192.34"
