apiVersion: v1
data:
  linear: '{"coresPerReplica":256,"nodesPerReplica":16,"preventSinglePointFailure":true}'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kube-dns-autoscaler
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-dns-autoscaler
