apiVersion: v1
data:
  provider-uid: d82b2a53ea47818a
  uid: d82b2a53ea47818a
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ingress-uid
  selfLink: /api/v1/namespaces/kube-system/configmaps/ingress-uid
