apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: kube-dns
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-dns
