apiVersion: v1
data:
  enable-vts-status: "false"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.31.0
    component: controller
    heritage: Tiller
    release: right-jaguar
  name: right-jaguar-nginx-ingress-controller
  selfLink: /api/v1/namespaces/kube-system/configmaps/right-jaguar-nginx-ingress-controller
