apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: kube-lego
    chart: kube-lego-0.4.2
    heritage: Tiller
    release: ignoble-starfish
  name: ignoble-starfish-kube-lego
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/ignoble-starfish-kube-lego
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-lego
      release: ignoble-starfish
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-lego
        release: ignoble-starfish
    spec:
      containers:
      - env:
        - name: LEGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LEGO_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: LEGO_EMAIL
          value: stuart@alphab.io
        - name: LEGO_PORT
          value: "8080"
        - name: LEGO_URL
          value: https://acme-v01.api.letsencrypt.org/directory
        image: jetstack/kube-lego:0.1.6
        imagePullPolicy: IfNotPresent
        name: kube-lego
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ignoble-starfish-kube-lego
      serviceAccountName: ignoble-starfish-kube-lego
      terminationGracePeriodSeconds: 30
status: {}
