apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/kube-lego-managed: "true"
  creationTimestamp: null
  name: kube-lego-nginx
  selfLink: /api/v1/namespaces/kube-system/services/kube-lego-nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube-lego
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
