apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.31.0
    component: default-backend
    heritage: Tiller
    release: right-jaguar
  name: right-jaguar-nginx-ingress-default-backend
  selfLink: /api/v1/namespaces/kube-system/services/right-jaguar-nginx-ingress-default-backend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx-ingress
    component: default-backend
    release: right-jaguar
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
