apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"run":"uw-api-graph-web"},"name":"uw-api-graph-web","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/uw-api-graph-web"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"uw-api-graph-web"}},"strategy":{"type":"RollingUpdate"},"template":{"metadata":{"labels":{"run":"uw-api-graph-web"}},"spec":{"containers":[{"image":"gcr.io/unicode-wiki/uw-api-graph:dev10.0","imagePullPolicy":"IfNotPresent","name":"uw-api-graph-web","ports":[{"containerPort":4000,"protocol":"TCP"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","terminationGracePeriodSeconds":30}}}}
  creationTimestamp: null
  generation: 1
  labels:
    run: uw-api-graph-web
  name: uw-api-graph-web
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/uw-api-graph-web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: uw-api-graph-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: uw-api-graph-web
    spec:
      containers:
      - image: gcr.io/unicode-wiki/uw-api-graph:1.2.0
        imagePullPolicy: IfNotPresent
        name: uw-api-graph-web
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
