apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: uw-wiki-service-web
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/uw-wiki-service-web
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: uw-wiki-service-web
  targetCPUUtilizationPercentage: 5
status:
  currentReplicas: 0
  desiredReplicas: 0
