apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"elasticsearch","release":"uw-mongo"},"name":"uw-elasticsearch","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"standard"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: elasticsearch
    release: uw-mongo
  name: uw-elasticsearch
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/uw-elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  volumeName: pvc-68470c11-fa28-11e8-809b-42010a8e014c
status: {}
