apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: null
  labels:
    app: mongodb
    chart: mongodb-4.9.0
    heritage: Tiller
    release: uw-mongo
  name: uw-mongo-mongodb
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/uw-mongo-mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeName: pvc-3a202db9-ea40-11e8-8766-42010a8e00c7
status: {}
