apiVersion: v1
data:
  tls.crt: ${tls.crt}
  tls.key: ${tls.key}
kind: Secret
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  creationTimestamp: null
  name: unicode-wiki-tls
  selfLink: /api/v1/namespaces/default/secrets/unicode-wiki-tls
type: kubernetes.io/tls
